### PR TITLE
When exporting from Inkscape, convert text nodes to paths

### PR DESCRIPTION
**Pull request by raboof**
First for review of the general approach. Of course the 2 duplicated methods
should be shared, can you recommend the idiomatic way to do that?

### CODE REVIEW

**Comment by raboof** [comment]
Refs #22

**Comment by frmdstryr** [comment]
This looks fine to me. 

Maybe it'd be good to move both extensions into a single `inkcut.py` or something and add it as a dependency in the `.inx` files.  

If the `<command>` tag supports just passing a flag or setting an env variable that would be the best but if not we can just have the `inkcut_cut.py` and `inkcut_open.py` files import from the common file.

**Comment by frmdstryr** [comment]
Let me know if this is done and i'll merge it in.

**Comment by raboof** [comment]
Ready from my side!

**Comment by frmdstryr** [comment]
Sorry i forgot. Can we also add the dependency to the .inx files?

**Pull request merged**
